### ISSUE TITLE
Hi first time doing this and I want to control my light switch from a http request but when i type the url in my web browser nothing happens. What am i supposed to put in the id and name? Also how is my config json looking is it correct?

### ISSUE THREAD

**Issue by Maarij12345** [benzman81/homebridge-http-webhooks#205] opened 2024-12-13 00:01 UTC
this is the light switch i want to control from my alexa plugin that is working from homekit: 
![image](https://github.com/user-attachments/assets/68d46c2a-d355-4b3a-92d8-da6e9c08ef42)
This is my json configuration 
![image](https://github.com/user-attachments/assets/85c9ae4d-79d7-4d01-b3ed-b4807b29471f)

{
            "platform": "HttpWebHooks",
            "webhook_port": "51828",
            "lights": [
                {
                    "id": "sconces",
                    "name": "sconces",
                    "on_url": "http://192.168.10.46:51828/?accessoryId=sconces&state=true",
                    "on_method": "GET",
                    "off_url": "http://192.168.10.46:51828/?accessoryId=sconces&state=false",
                    "off_method": "GET"
                }
            ]
        }
    ]
}

**Comment by benzman81** [comment] 2024-12-13 06:07
You are trying to trigger yourself, which is not possbile/makes no sense. In the url you need to put the urls to turn on/off your lightbulb.

**Comment by jsiegenthaler** [comment] 2024-12-13 12:40
@benzman81 I think that the root cause here is a documentation issue: I'll do a PR with an improvement to the documentation

**Comment by jsiegenthaler** [comment] 2024-12-13 13:08
I added PR #206 with updates to the Readme

**Comment by benzman81** [comment] 2024-12-13 13:28
@jsiegenthaler merged pr to make it clearer.

**Closed by benzman81** 2024-12-13 13:28 UTC
