### ISSUE TITLE
Cant't connect to a homebridge existing device

### ISSUE THREAD

**Issue by D-Greengo** [benzman81/homebridge-http-webhooks#167] opened 2022-09-25 13:23 UTC
Hi thanks for the great plugin.
I have installed and now I can control homebridge truth http, its nice but i'm only can control a new device created after the plugin config.
Is that a way to config the plugin to directly control the existing devices in my homebridge?

**Comment by benzman81** [comment] 2022-09-25 14:24
Duplicate of #120

**Closed by benzman81** 2022-09-25 14:24 UTC
Labels: duplicate
